import { CartService } from "./cart.service";
describe("CartService", () => {
    let cartService;
    let mockCartRepository;
    let mockProductServiceAdapter; // This will be mocked but not used in clearCartByUserId tests
    beforeEach(() => {
        mockCartRepository = {
            findByUserId: jest.fn(),
            save: jest.fn(),
        };
        // Mocking only the necessary part, or keep it minimal if not used
        mockProductServiceAdapter = {
            getProductById: jest.fn(),
        }; // Cast to avoid strict type checking for unused methods/properties
        cartService = new CartService(mockCartRepository, mockProductServiceAdapter);
    });
    describe("clearCartByUserId", () => {
        const userIdString = "12345"; // Test userId as string (UUID-like)
        const userIdNumber = Number(userIdString); // Converted for internal repository usage
        it("should clear the cart for a given user ID if a cart exists", async () => {
            // Arrange
            const existingCart = {
                id: 1, // Assume an ID is generated by the DB for the saved cart
                userId: userIdNumber,
                items: [{ id: 101, productId: 1, quantity: 2 }],
                createdAt: new Date(),
                updatedAt: new Date(),
            };
            mockCartRepository.findByUserId.mockResolvedValue(existingCart);
            // Mock save to return the modified cart with an ID
            mockCartRepository.save.mockImplementation(async (cart) => ({ ...cart, id: 1 }));
            // Act
            await cartService.clearCartByUserId(userIdString);
            // Assert
            expect(mockCartRepository.findByUserId).toHaveBeenCalledWith(userIdNumber);
            expect(mockCartRepository.save).toHaveBeenCalledTimes(1);
            const savedCart = mockCartRepository.save.mock.calls[0]?.[0]; // Get the cart that was passed to save, with safe access
            expect(savedCart).toBeDefined();
            expect(savedCart?.items).toEqual([]);
            expect(savedCart?.updatedAt).toBeInstanceOf(Date); // Check if updated timestamp is set
        });
        it("should do nothing if no cart is found for the user ID", async () => {
            // Arrange
            mockCartRepository.findByUserId.mockResolvedValue(null); // No cart found
            mockCartRepository.save.mockImplementation(async (cart) => ({ ...cart, id: 1 }));
            // Act
            await cartService.clearCartByUserId(userIdString);
            // Assert
            expect(mockCartRepository.findByUserId).toHaveBeenCalledWith(userIdNumber);
            expect(mockCartRepository.save).not.toHaveBeenCalled(); // Should not attempt to save
        });
    });
});
//# sourceMappingURL=cart.service.test.js.map