import { CartService } from "./cart.service.js";
import type { Cart, CartItem } from "../models/cart.js";
import type { CartRepository } from "../repositories/CartRepository.js";
import type { ProductServiceAdapter } from "../adapters/ProductServiceAdapter.js";

describe("CartService", () => {
  let cartService: CartService;
  let mockCartRepository: jest.Mocked<CartRepository>;
  let mockProductServiceAdapter: jest.Mocked<ProductServiceAdapter>; // This will be mocked but not used in clearCartByUserId tests

  beforeEach(() => {
    mockCartRepository = {
      findByUserId: jest.fn(),
      save: jest.fn(),
    };
    // Mocking only the necessary part, or keep it minimal if not used
    mockProductServiceAdapter = {
      getProductById: jest.fn(),
    } as unknown as jest.Mocked<ProductServiceAdapter>; // Cast to avoid strict type checking for unused methods/properties
    cartService = new CartService(
      mockCartRepository,
      mockProductServiceAdapter,
    );
  });

  describe("clearCartByUserId", () => {
    const userIdString = "12345"; // Test userId as string (UUID-like)
    const userIdNumber = Number(userIdString); // Converted for internal repository usage

    it("should clear the cart for a given user ID if a cart exists", async () => {
      // Arrange
      const existingCart: Cart = {
        id: 1, // Assume an ID is generated by the DB for the saved cart
        userId: userIdNumber,
        items: [{ id: 101, productId: 1, quantity: 2 }],
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      mockCartRepository.findByUserId.mockResolvedValue(existingCart);
      mockCartRepository.save.mockImplementation(async (cart: Omit<Cart, "id"> | Cart) => ({ ...cart as Cart, id: 1 })); 

      // Act
      await cartService.clearCartByUserId(userIdString);

      // Assert
      expect(mockCartRepository.findByUserId).toHaveBeenCalledWith(userIdNumber);
      expect(mockCartRepository.save).toHaveBeenCalledTimes(1);
      const savedCart = mockCartRepository.save.mock.calls[0]?.[0]; // Get the cart that was passed to save, with safe access
      expect(savedCart).toBeDefined();
      expect(savedCart?.items).toEqual([]);
      expect(savedCart?.updatedAt).toBeInstanceOf(Date); // Check if updated timestamp is set
    });

    it("should do nothing if no cart is found for the user ID", async () => {
      // Arrange
      mockCartRepository.findByUserId.mockResolvedValue(null); // No cart found
      mockCartRepository.save.mockImplementation(async (cart: Omit<Cart, "id"> | Cart) => ({ ...cart as Cart, id: 1 }));

      // Act
      await cartService.clearCartByUserId(userIdString);

      // Assert
      expect(mockCartRepository.findByUserId).toHaveBeenCalledWith(userIdNumber);
      expect(mockCartRepository.save).not.toHaveBeenCalled(); // Should not attempt to save
    });
  });
});
