apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-audit-service
  labels:
    app: audit-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
