apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory-write
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: inventory-write
