apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-category
  labels:
    app: category
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
