// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: agent.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  ClientReadableStream,
  handleServerStreamingCall,
  makeGenericClientConstructor,
  Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { Value } from "./google/protobuf/struct";

export const protobufPackage = "agent.v1";

/** The request message for the ExecuteWorkflow RPC. */
export interface ExecuteWorkflowRequest {
  userQuery: string;
}

/** The response message for the ExecuteWorkflow RPC. */
export interface ExecuteWorkflowResponse {
  workflowStarted?: WorkflowStartedEvent | undefined;
  toolStarted?: ToolStartedEvent | undefined;
  toolEnded?: ToolEndedEvent | undefined;
  workflowEnded?: WorkflowEndedEvent | undefined;
  workflowError?: WorkflowErrorEvent | undefined;
}

export interface WorkflowStartedEvent {
  workflowId: string;
}

export interface ToolStartedEvent {
  toolName: string;
  input: any | undefined;
}

export interface ToolEndedEvent {
  toolName: string;
  output: any | undefined;
}

export interface WorkflowEndedEvent {
  finalResponse: string;
}

export interface WorkflowErrorEvent {
  errorMessage: string;
}

function createBaseExecuteWorkflowRequest(): ExecuteWorkflowRequest {
  return { userQuery: "" };
}

export const ExecuteWorkflowRequest = {
  encode(
    message: ExecuteWorkflowRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.userQuery !== "") {
      writer.uint32(10).string(message.userQuery);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): ExecuteWorkflowRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteWorkflowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userQuery = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteWorkflowRequest {
    return {
      userQuery: isSet(object.userQuery)
        ? globalThis.String(object.userQuery)
        : "",
    };
  },

  toJSON(message: ExecuteWorkflowRequest): unknown {
    const obj: any = {};
    if (message.userQuery !== "") {
      obj.userQuery = message.userQuery;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteWorkflowRequest>, I>>(
    base?: I,
  ): ExecuteWorkflowRequest {
    return ExecuteWorkflowRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteWorkflowRequest>, I>>(
    object: I,
  ): ExecuteWorkflowRequest {
    const message = createBaseExecuteWorkflowRequest();
    message.userQuery = object.userQuery ?? "";
    return message;
  },
};

function createBaseExecuteWorkflowResponse(): ExecuteWorkflowResponse {
  return {
    workflowStarted: undefined,
    toolStarted: undefined,
    toolEnded: undefined,
    workflowEnded: undefined,
    workflowError: undefined,
  };
}

export const ExecuteWorkflowResponse = {
  encode(
    message: ExecuteWorkflowResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.workflowStarted !== undefined) {
      WorkflowStartedEvent.encode(
        message.workflowStarted,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.toolStarted !== undefined) {
      ToolStartedEvent.encode(
        message.toolStarted,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.toolEnded !== undefined) {
      ToolEndedEvent.encode(
        message.toolEnded,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    if (message.workflowEnded !== undefined) {
      WorkflowEndedEvent.encode(
        message.workflowEnded,
        writer.uint32(34).fork(),
      ).ldelim();
    }
    if (message.workflowError !== undefined) {
      WorkflowErrorEvent.encode(
        message.workflowError,
        writer.uint32(42).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): ExecuteWorkflowResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteWorkflowResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.workflowStarted = WorkflowStartedEvent.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.toolStarted = ToolStartedEvent.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.toolEnded = ToolEndedEvent.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.workflowEnded = WorkflowEndedEvent.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.workflowError = WorkflowErrorEvent.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteWorkflowResponse {
    return {
      workflowStarted: isSet(object.workflowStarted)
        ? WorkflowStartedEvent.fromJSON(object.workflowStarted)
        : undefined,
      toolStarted: isSet(object.toolStarted)
        ? ToolStartedEvent.fromJSON(object.toolStarted)
        : undefined,
      toolEnded: isSet(object.toolEnded)
        ? ToolEndedEvent.fromJSON(object.toolEnded)
        : undefined,
      workflowEnded: isSet(object.workflowEnded)
        ? WorkflowEndedEvent.fromJSON(object.workflowEnded)
        : undefined,
      workflowError: isSet(object.workflowError)
        ? WorkflowErrorEvent.fromJSON(object.workflowError)
        : undefined,
    };
  },

  toJSON(message: ExecuteWorkflowResponse): unknown {
    const obj: any = {};
    if (message.workflowStarted !== undefined) {
      obj.workflowStarted = WorkflowStartedEvent.toJSON(
        message.workflowStarted,
      );
    }
    if (message.toolStarted !== undefined) {
      obj.toolStarted = ToolStartedEvent.toJSON(message.toolStarted);
    }
    if (message.toolEnded !== undefined) {
      obj.toolEnded = ToolEndedEvent.toJSON(message.toolEnded);
    }
    if (message.workflowEnded !== undefined) {
      obj.workflowEnded = WorkflowEndedEvent.toJSON(message.workflowEnded);
    }
    if (message.workflowError !== undefined) {
      obj.workflowError = WorkflowErrorEvent.toJSON(message.workflowError);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteWorkflowResponse>, I>>(
    base?: I,
  ): ExecuteWorkflowResponse {
    return ExecuteWorkflowResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteWorkflowResponse>, I>>(
    object: I,
  ): ExecuteWorkflowResponse {
    const message = createBaseExecuteWorkflowResponse();
    message.workflowStarted =
      object.workflowStarted !== undefined && object.workflowStarted !== null
        ? WorkflowStartedEvent.fromPartial(object.workflowStarted)
        : undefined;
    message.toolStarted =
      object.toolStarted !== undefined && object.toolStarted !== null
        ? ToolStartedEvent.fromPartial(object.toolStarted)
        : undefined;
    message.toolEnded =
      object.toolEnded !== undefined && object.toolEnded !== null
        ? ToolEndedEvent.fromPartial(object.toolEnded)
        : undefined;
    message.workflowEnded =
      object.workflowEnded !== undefined && object.workflowEnded !== null
        ? WorkflowEndedEvent.fromPartial(object.workflowEnded)
        : undefined;
    message.workflowError =
      object.workflowError !== undefined && object.workflowError !== null
        ? WorkflowErrorEvent.fromPartial(object.workflowError)
        : undefined;
    return message;
  },
};

function createBaseWorkflowStartedEvent(): WorkflowStartedEvent {
  return { workflowId: "" };
}

export const WorkflowStartedEvent = {
  encode(
    message: WorkflowStartedEvent,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.workflowId !== "") {
      writer.uint32(10).string(message.workflowId);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): WorkflowStartedEvent {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflowStartedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.workflowId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkflowStartedEvent {
    return {
      workflowId: isSet(object.workflowId)
        ? globalThis.String(object.workflowId)
        : "",
    };
  },

  toJSON(message: WorkflowStartedEvent): unknown {
    const obj: any = {};
    if (message.workflowId !== "") {
      obj.workflowId = message.workflowId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkflowStartedEvent>, I>>(
    base?: I,
  ): WorkflowStartedEvent {
    return WorkflowStartedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkflowStartedEvent>, I>>(
    object: I,
  ): WorkflowStartedEvent {
    const message = createBaseWorkflowStartedEvent();
    message.workflowId = object.workflowId ?? "";
    return message;
  },
};

function createBaseToolStartedEvent(): ToolStartedEvent {
  return { toolName: "", input: undefined };
}

export const ToolStartedEvent = {
  encode(
    message: ToolStartedEvent,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.toolName !== "") {
      writer.uint32(10).string(message.toolName);
    }
    if (message.input !== undefined) {
      Value.encode(
        Value.wrap(message.input),
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ToolStartedEvent {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolStartedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.toolName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.input = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolStartedEvent {
    return {
      toolName: isSet(object.toolName)
        ? globalThis.String(object.toolName)
        : "",
      input: isSet(object?.input) ? object.input : undefined,
    };
  },

  toJSON(message: ToolStartedEvent): unknown {
    const obj: any = {};
    if (message.toolName !== "") {
      obj.toolName = message.toolName;
    }
    if (message.input !== undefined) {
      obj.input = message.input;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolStartedEvent>, I>>(
    base?: I,
  ): ToolStartedEvent {
    return ToolStartedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolStartedEvent>, I>>(
    object: I,
  ): ToolStartedEvent {
    const message = createBaseToolStartedEvent();
    message.toolName = object.toolName ?? "";
    message.input = object.input ?? undefined;
    return message;
  },
};

function createBaseToolEndedEvent(): ToolEndedEvent {
  return { toolName: "", output: undefined };
}

export const ToolEndedEvent = {
  encode(
    message: ToolEndedEvent,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.toolName !== "") {
      writer.uint32(10).string(message.toolName);
    }
    if (message.output !== undefined) {
      Value.encode(
        Value.wrap(message.output),
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ToolEndedEvent {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolEndedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.toolName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.output = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolEndedEvent {
    return {
      toolName: isSet(object.toolName)
        ? globalThis.String(object.toolName)
        : "",
      output: isSet(object?.output) ? object.output : undefined,
    };
  },

  toJSON(message: ToolEndedEvent): unknown {
    const obj: any = {};
    if (message.toolName !== "") {
      obj.toolName = message.toolName;
    }
    if (message.output !== undefined) {
      obj.output = message.output;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolEndedEvent>, I>>(
    base?: I,
  ): ToolEndedEvent {
    return ToolEndedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolEndedEvent>, I>>(
    object: I,
  ): ToolEndedEvent {
    const message = createBaseToolEndedEvent();
    message.toolName = object.toolName ?? "";
    message.output = object.output ?? undefined;
    return message;
  },
};

function createBaseWorkflowEndedEvent(): WorkflowEndedEvent {
  return { finalResponse: "" };
}

export const WorkflowEndedEvent = {
  encode(
    message: WorkflowEndedEvent,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.finalResponse !== "") {
      writer.uint32(10).string(message.finalResponse);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): WorkflowEndedEvent {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflowEndedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.finalResponse = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkflowEndedEvent {
    return {
      finalResponse: isSet(object.finalResponse)
        ? globalThis.String(object.finalResponse)
        : "",
    };
  },

  toJSON(message: WorkflowEndedEvent): unknown {
    const obj: any = {};
    if (message.finalResponse !== "") {
      obj.finalResponse = message.finalResponse;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkflowEndedEvent>, I>>(
    base?: I,
  ): WorkflowEndedEvent {
    return WorkflowEndedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkflowEndedEvent>, I>>(
    object: I,
  ): WorkflowEndedEvent {
    const message = createBaseWorkflowEndedEvent();
    message.finalResponse = object.finalResponse ?? "";
    return message;
  },
};

function createBaseWorkflowErrorEvent(): WorkflowErrorEvent {
  return { errorMessage: "" };
}

export const WorkflowErrorEvent = {
  encode(
    message: WorkflowErrorEvent,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.errorMessage !== "") {
      writer.uint32(10).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): WorkflowErrorEvent {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflowErrorEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkflowErrorEvent {
    return {
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : "",
    };
  },

  toJSON(message: WorkflowErrorEvent): unknown {
    const obj: any = {};
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkflowErrorEvent>, I>>(
    base?: I,
  ): WorkflowErrorEvent {
    return WorkflowErrorEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkflowErrorEvent>, I>>(
    object: I,
  ): WorkflowErrorEvent {
    const message = createBaseWorkflowErrorEvent();
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

/** The Agent service definition. */
export type AgentServiceService = typeof AgentServiceService;
export const AgentServiceService = {
  /**
   * Executes a workflow based on a user query.
   * This is a streaming RPC, allowing for real-time updates on the workflow's progress.
   */
  executeWorkflow: {
    path: "/agent.v1.AgentService/ExecuteWorkflow",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: ExecuteWorkflowRequest) =>
      Buffer.from(ExecuteWorkflowRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ExecuteWorkflowRequest.decode(value),
    responseSerialize: (value: ExecuteWorkflowResponse) =>
      Buffer.from(ExecuteWorkflowResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) =>
      ExecuteWorkflowResponse.decode(value),
  },
} as const;

export interface AgentServiceServer extends UntypedServiceImplementation {
  /**
   * Executes a workflow based on a user query.
   * This is a streaming RPC, allowing for real-time updates on the workflow's progress.
   */
  executeWorkflow: handleServerStreamingCall<
    ExecuteWorkflowRequest,
    ExecuteWorkflowResponse
  >;
}

export interface AgentServiceClient extends Client {
  /**
   * Executes a workflow based on a user query.
   * This is a streaming RPC, allowing for real-time updates on the workflow's progress.
   */
  executeWorkflow(
    request: ExecuteWorkflowRequest,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ExecuteWorkflowResponse>;
  executeWorkflow(
    request: ExecuteWorkflowRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ExecuteWorkflowResponse>;
}

export const AgentServiceClient = makeGenericClientConstructor(
  AgentServiceService,
  "agent.v1.AgentService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): AgentServiceClient;
  service: typeof AgentServiceService;
  serviceName: string;
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
