// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: cart.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "cart";

/** Represents a single item in the shopping cart */
export interface CartItem {
  productId: string;
  quantity: number;
  /** Denormalized product name */
  name: string;
  /** Denormalized price at the time of adding, in cents */
  priceCents: number;
  /** Denormalized product image URL */
  imageUrl: string;
}

/** Represents a user's shopping cart */
export interface Cart {
  userId: string;
  items: CartItem[];
  totalPriceCents: number;
  totalDiscountCents: number;
  totalTaxCents: number;
}

export interface AddItemToCartRequest {
  userId: string;
  productId: string;
  quantity: number;
}

export interface UpdateItemQuantityRequest {
  userId: string;
  productId: string;
  /** The new quantity for the item */
  quantity: number;
}

export interface RemoveItemFromCartRequest {
  userId: string;
  productId: string;
}

export interface GetCartRequest {
  userId: string;
}

/** Common response for cart operations, includes the updated cart state */
export interface CartResponse {
  /**
   * You could add a status field here if the operation has specific outcomes
   * string status_message = 2;
   */
  cart: Cart | undefined;
}

function createBaseCartItem(): CartItem {
  return { productId: "", quantity: 0, name: "", priceCents: 0, imageUrl: "" };
}

export const CartItem = {
  encode(
    message: CartItem,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.priceCents !== 0) {
      writer.uint32(32).int64(message.priceCents);
    }
    if (message.imageUrl !== "") {
      writer.uint32(42).string(message.imageUrl);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CartItem {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCartItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.priceCents = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.imageUrl = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CartItem {
    return {
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      priceCents: isSet(object.priceCents)
        ? globalThis.Number(object.priceCents)
        : 0,
      imageUrl: isSet(object.imageUrl)
        ? globalThis.String(object.imageUrl)
        : "",
    };
  },

  toJSON(message: CartItem): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.priceCents !== 0) {
      obj.priceCents = Math.round(message.priceCents);
    }
    if (message.imageUrl !== "") {
      obj.imageUrl = message.imageUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CartItem>, I>>(base?: I): CartItem {
    return CartItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CartItem>, I>>(object: I): CartItem {
    const message = createBaseCartItem();
    message.productId = object.productId ?? "";
    message.quantity = object.quantity ?? 0;
    message.name = object.name ?? "";
    message.priceCents = object.priceCents ?? 0;
    message.imageUrl = object.imageUrl ?? "";
    return message;
  },
};

function createBaseCart(): Cart {
  return {
    userId: "",
    items: [],
    totalPriceCents: 0,
    totalDiscountCents: 0,
    totalTaxCents: 0,
  };
}

export const Cart = {
  encode(message: Cart, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    for (const v of message.items) {
      CartItem.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    if (message.totalPriceCents !== 0) {
      writer.uint32(24).int64(message.totalPriceCents);
    }
    if (message.totalDiscountCents !== 0) {
      writer.uint32(32).int64(message.totalDiscountCents);
    }
    if (message.totalTaxCents !== 0) {
      writer.uint32(40).int64(message.totalTaxCents);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Cart {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.items.push(CartItem.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.totalPriceCents = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalDiscountCents = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.totalTaxCents = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Cart {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => CartItem.fromJSON(e))
        : [],
      totalPriceCents: isSet(object.totalPriceCents)
        ? globalThis.Number(object.totalPriceCents)
        : 0,
      totalDiscountCents: isSet(object.totalDiscountCents)
        ? globalThis.Number(object.totalDiscountCents)
        : 0,
      totalTaxCents: isSet(object.totalTaxCents)
        ? globalThis.Number(object.totalTaxCents)
        : 0,
    };
  },

  toJSON(message: Cart): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => CartItem.toJSON(e));
    }
    if (message.totalPriceCents !== 0) {
      obj.totalPriceCents = Math.round(message.totalPriceCents);
    }
    if (message.totalDiscountCents !== 0) {
      obj.totalDiscountCents = Math.round(message.totalDiscountCents);
    }
    if (message.totalTaxCents !== 0) {
      obj.totalTaxCents = Math.round(message.totalTaxCents);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Cart>, I>>(base?: I): Cart {
    return Cart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Cart>, I>>(object: I): Cart {
    const message = createBaseCart();
    message.userId = object.userId ?? "";
    message.items = object.items?.map((e) => CartItem.fromPartial(e)) || [];
    message.totalPriceCents = object.totalPriceCents ?? 0;
    message.totalDiscountCents = object.totalDiscountCents ?? 0;
    message.totalTaxCents = object.totalTaxCents ?? 0;
    return message;
  },
};

function createBaseAddItemToCartRequest(): AddItemToCartRequest {
  return { userId: "", productId: "", quantity: 0 };
}

export const AddItemToCartRequest = {
  encode(
    message: AddItemToCartRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.productId !== "") {
      writer.uint32(18).string(message.productId);
    }
    if (message.quantity !== 0) {
      writer.uint32(24).int32(message.quantity);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): AddItemToCartRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddItemToCartRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.productId = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddItemToCartRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: AddItemToCartRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddItemToCartRequest>, I>>(
    base?: I,
  ): AddItemToCartRequest {
    return AddItemToCartRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddItemToCartRequest>, I>>(
    object: I,
  ): AddItemToCartRequest {
    const message = createBaseAddItemToCartRequest();
    message.userId = object.userId ?? "";
    message.productId = object.productId ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseUpdateItemQuantityRequest(): UpdateItemQuantityRequest {
  return { userId: "", productId: "", quantity: 0 };
}

export const UpdateItemQuantityRequest = {
  encode(
    message: UpdateItemQuantityRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.productId !== "") {
      writer.uint32(18).string(message.productId);
    }
    if (message.quantity !== 0) {
      writer.uint32(24).int32(message.quantity);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): UpdateItemQuantityRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateItemQuantityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.productId = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateItemQuantityRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: UpdateItemQuantityRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateItemQuantityRequest>, I>>(
    base?: I,
  ): UpdateItemQuantityRequest {
    return UpdateItemQuantityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateItemQuantityRequest>, I>>(
    object: I,
  ): UpdateItemQuantityRequest {
    const message = createBaseUpdateItemQuantityRequest();
    message.userId = object.userId ?? "";
    message.productId = object.productId ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseRemoveItemFromCartRequest(): RemoveItemFromCartRequest {
  return { userId: "", productId: "" };
}

export const RemoveItemFromCartRequest = {
  encode(
    message: RemoveItemFromCartRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.productId !== "") {
      writer.uint32(18).string(message.productId);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): RemoveItemFromCartRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveItemFromCartRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.productId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveItemFromCartRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
    };
  },

  toJSON(message: RemoveItemFromCartRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveItemFromCartRequest>, I>>(
    base?: I,
  ): RemoveItemFromCartRequest {
    return RemoveItemFromCartRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveItemFromCartRequest>, I>>(
    object: I,
  ): RemoveItemFromCartRequest {
    const message = createBaseRemoveItemFromCartRequest();
    message.userId = object.userId ?? "";
    message.productId = object.productId ?? "";
    return message;
  },
};

function createBaseGetCartRequest(): GetCartRequest {
  return { userId: "" };
}

export const GetCartRequest = {
  encode(
    message: GetCartRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetCartRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCartRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCartRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
    };
  },

  toJSON(message: GetCartRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCartRequest>, I>>(
    base?: I,
  ): GetCartRequest {
    return GetCartRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCartRequest>, I>>(
    object: I,
  ): GetCartRequest {
    const message = createBaseGetCartRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseCartResponse(): CartResponse {
  return { cart: undefined };
}

export const CartResponse = {
  encode(
    message: CartResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.cart !== undefined) {
      Cart.encode(message.cart, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CartResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCartResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.cart = Cart.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CartResponse {
    return {
      cart: isSet(object.cart) ? Cart.fromJSON(object.cart) : undefined,
    };
  },

  toJSON(message: CartResponse): unknown {
    const obj: any = {};
    if (message.cart !== undefined) {
      obj.cart = Cart.toJSON(message.cart);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CartResponse>, I>>(
    base?: I,
  ): CartResponse {
    return CartResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CartResponse>, I>>(
    object: I,
  ): CartResponse {
    const message = createBaseCartResponse();
    message.cart =
      object.cart !== undefined && object.cart !== null
        ? Cart.fromPartial(object.cart)
        : undefined;
    return message;
  },
};

/** --- CartService Definition --- */
export type CartServiceService = typeof CartServiceService;
export const CartServiceService = {
  /** Adds an item to the user's cart or updates its quantity if already present */
  addItemToCart: {
    path: "/cart.CartService/AddItemToCart",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AddItemToCartRequest) =>
      Buffer.from(AddItemToCartRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AddItemToCartRequest.decode(value),
    responseSerialize: (value: CartResponse) =>
      Buffer.from(CartResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CartResponse.decode(value),
  },
  /** Updates the quantity of an existing item in the cart */
  updateItemQuantity: {
    path: "/cart.CartService/UpdateItemQuantity",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateItemQuantityRequest) =>
      Buffer.from(UpdateItemQuantityRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) =>
      UpdateItemQuantityRequest.decode(value),
    responseSerialize: (value: CartResponse) =>
      Buffer.from(CartResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CartResponse.decode(value),
  },
  /** Removes an item from the user's cart */
  removeItemFromCart: {
    path: "/cart.CartService/RemoveItemFromCart",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RemoveItemFromCartRequest) =>
      Buffer.from(RemoveItemFromCartRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) =>
      RemoveItemFromCartRequest.decode(value),
    responseSerialize: (value: CartResponse) =>
      Buffer.from(CartResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CartResponse.decode(value),
  },
  /** Retrieves the current state of the user's cart */
  getCart: {
    path: "/cart.CartService/GetCart",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetCartRequest) =>
      Buffer.from(GetCartRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetCartRequest.decode(value),
    responseSerialize: (value: CartResponse) =>
      Buffer.from(CartResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CartResponse.decode(value),
  },
} as const;

export interface CartServiceServer extends UntypedServiceImplementation {
  /** Adds an item to the user's cart or updates its quantity if already present */
  addItemToCart: handleUnaryCall<AddItemToCartRequest, CartResponse>;
  /** Updates the quantity of an existing item in the cart */
  updateItemQuantity: handleUnaryCall<UpdateItemQuantityRequest, CartResponse>;
  /** Removes an item from the user's cart */
  removeItemFromCart: handleUnaryCall<RemoveItemFromCartRequest, CartResponse>;
  /** Retrieves the current state of the user's cart */
  getCart: handleUnaryCall<GetCartRequest, CartResponse>;
}

export interface CartServiceClient extends Client {
  /** Adds an item to the user's cart or updates its quantity if already present */
  addItemToCart(
    request: AddItemToCartRequest,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  addItemToCart(
    request: AddItemToCartRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  addItemToCart(
    request: AddItemToCartRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  /** Updates the quantity of an existing item in the cart */
  updateItemQuantity(
    request: UpdateItemQuantityRequest,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  updateItemQuantity(
    request: UpdateItemQuantityRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  updateItemQuantity(
    request: UpdateItemQuantityRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  /** Removes an item from the user's cart */
  removeItemFromCart(
    request: RemoveItemFromCartRequest,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  removeItemFromCart(
    request: RemoveItemFromCartRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  removeItemFromCart(
    request: RemoveItemFromCartRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  /** Retrieves the current state of the user's cart */
  getCart(
    request: GetCartRequest,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  getCart(
    request: GetCartRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
  getCart(
    request: GetCartRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CartResponse) => void,
  ): ClientUnaryCall;
}

export const CartServiceClient = makeGenericClientConstructor(
  CartServiceService,
  "cart.CartService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): CartServiceClient;
  service: typeof CartServiceService;
  serviceName: string;
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
