# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x08\x61gent.v1\x1a\x1cgoogle/protobuf/struct.proto\",\n\x16\x45xecuteWorkflowRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\"\xb2\x02\n\x17\x45xecuteWorkflowResponse\x12:\n\x10workflow_started\x18\x01 \x01(\x0b\x32\x1e.agent.v1.WorkflowStartedEventH\x00\x12\x32\n\x0ctool_started\x18\x02 \x01(\x0b\x32\x1a.agent.v1.ToolStartedEventH\x00\x12.\n\ntool_ended\x18\x03 \x01(\x0b\x32\x18.agent.v1.ToolEndedEventH\x00\x12\x36\n\x0eworkflow_ended\x18\x04 \x01(\x0b\x32\x1c.agent.v1.WorkflowEndedEventH\x00\x12\x36\n\x0eworkflow_error\x18\x05 \x01(\x0b\x32\x1c.agent.v1.WorkflowErrorEventH\x00\x42\x07\n\x05\x65vent\"+\n\x14WorkflowStartedEvent\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\"L\n\x10ToolStartedEvent\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12%\n\x05input\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\"K\n\x0eToolEndedEvent\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12&\n\x06output\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\",\n\x12WorkflowEndedEvent\x12\x16\n\x0e\x66inal_response\x18\x01 \x01(\t\"+\n\x12WorkflowErrorEvent\x12\x15\n\rerror_message\x18\x01 \x01(\t2h\n\x0c\x41gentService\x12X\n\x0f\x45xecuteWorkflow\x12 .agent.v1.ExecuteWorkflowRequest\x1a!.agent.v1.ExecuteWorkflowResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXECUTEWORKFLOWREQUEST._serialized_start=55
  _EXECUTEWORKFLOWREQUEST._serialized_end=99
  _EXECUTEWORKFLOWRESPONSE._serialized_start=102
  _EXECUTEWORKFLOWRESPONSE._serialized_end=408
  _WORKFLOWSTARTEDEVENT._serialized_start=410
  _WORKFLOWSTARTEDEVENT._serialized_end=453
  _TOOLSTARTEDEVENT._serialized_start=455
  _TOOLSTARTEDEVENT._serialized_end=531
  _TOOLENDEDEVENT._serialized_start=533
  _TOOLENDEDEVENT._serialized_end=608
  _WORKFLOWENDEDEVENT._serialized_start=610
  _WORKFLOWENDEDEVENT._serialized_end=654
  _WORKFLOWERROREVENT._serialized_start=656
  _WORKFLOWERROREVENT._serialized_end=699
  _AGENTSERVICE._serialized_start=701
  _AGENTSERVICE._serialized_end=805
# @@protoc_insertion_point(module_scope)
