# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x0c\x61uth_service\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\\\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\r\n\x05roles\x18\x04 \x03(\t2g\n\x0b\x41uthService\x12X\n\rValidateToken\x12\".auth_service.ValidateTokenRequest\x1a#.auth_service.ValidateTokenResponseB\"\n\x0c\x61uth_serviceB\x10\x41uthServiceProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014auth_serviceB\020AuthServiceProtoP\001'
  _VALIDATETOKENREQUEST._serialized_start=36
  _VALIDATETOKENREQUEST._serialized_end=73
  _VALIDATETOKENRESPONSE._serialized_start=75
  _VALIDATETOKENRESPONSE._serialized_end=167
  _AUTHSERVICE._serialized_start=169
  _AUTHSERVICE._serialized_end=272
# @@protoc_insertion_point(module_scope)
