# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart_snapshot_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cart_pb2 as cart__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63\x61rt_snapshot_service.proto\x12\x15\x63\x61rt_snapshot_service\x1a\ncart.proto\"\xd3\x01\n\x0c\x43\x61rtSnapshot\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1d\n\x05items\x18\x03 \x03(\x0b\x32\x0e.cart.CartItem\x12\x19\n\x11total_price_cents\x18\x04 \x01(\x03\x12\x1c\n\x14total_discount_cents\x18\x05 \x01(\x03\x12\x17\n\x0ftotal_tax_cents\x18\x06 \x01(\x03\x12\x18\n\x10shipping_address\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\"\xbc\x01\n\x19\x43reateCartSnapshotRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\"\n\ncart_items\x18\x02 \x03(\x0b\x32\x0e.cart.CartItem\x12\x19\n\x11total_price_cents\x18\x03 \x01(\x03\x12\x1c\n\x14total_discount_cents\x18\x04 \x01(\x03\x12\x17\n\x0ftotal_tax_cents\x18\x05 \x01(\x03\x12\x18\n\x10shipping_address\x18\x06 \x01(\t\"S\n\x1a\x43reateCartSnapshotResponse\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"-\n\x16GetCartSnapshotRequest\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\"o\n\x14\x43\x61rtSnapshotResponse\x12\x35\n\x08snapshot\x18\x01 \x01(\x0b\x32#.cart_snapshot_service.CartSnapshot\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\xff\x01\n\x13\x43\x61rtSnapshotService\x12y\n\x12\x43reateCartSnapshot\x12\x30.cart_snapshot_service.CreateCartSnapshotRequest\x1a\x31.cart_snapshot_service.CreateCartSnapshotResponse\x12m\n\x0fGetCartSnapshot\x12-.cart_snapshot_service.GetCartSnapshotRequest\x1a+.cart_snapshot_service.CartSnapshotResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_snapshot_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARTSNAPSHOT._serialized_start=67
  _CARTSNAPSHOT._serialized_end=278
  _CREATECARTSNAPSHOTREQUEST._serialized_start=281
  _CREATECARTSNAPSHOTREQUEST._serialized_end=469
  _CREATECARTSNAPSHOTRESPONSE._serialized_start=471
  _CREATECARTSNAPSHOTRESPONSE._serialized_end=554
  _GETCARTSNAPSHOTREQUEST._serialized_start=556
  _GETCARTSNAPSHOTREQUEST._serialized_end=601
  _CARTSNAPSHOTRESPONSE._serialized_start=603
  _CARTSNAPSHOTRESPONSE._serialized_end=714
  _CARTSNAPSHOTSERVICE._serialized_start=717
  _CARTSNAPSHOTSERVICE._serialized_end=972
# @@protoc_insertion_point(module_scope)
