# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\x04\x63\x61rt\"f\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bprice_cents\x18\x04 \x01(\x03\x12\x11\n\timage_url\x18\x05 \x01(\t\"6\n\x04\x43\x61rt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.cart.CartItem\"M\n\x14\x41\x64\x64ItemToCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"R\n\x19UpdateItemQuantityRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"@\n\x19RemoveItemFromCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"!\n\x0eGetCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"(\n\x0c\x43\x61rtResponse\x12\x18\n\x04\x63\x61rt\x18\x01 \x01(\x0b\x32\n.cart.Cart2\x99\x02\n\x0b\x43\x61rtService\x12?\n\rAddItemToCart\x12\x1a.cart.AddItemToCartRequest\x1a\x12.cart.CartResponse\x12I\n\x12UpdateItemQuantity\x12\x1f.cart.UpdateItemQuantityRequest\x1a\x12.cart.CartResponse\x12I\n\x12RemoveItemFromCart\x12\x1f.cart.RemoveItemFromCartRequest\x1a\x12.cart.CartResponse\x12\x33\n\x07GetCart\x12\x14.cart.GetCartRequest\x1a\x12.cart.CartResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARTITEM._serialized_start=20
  _CARTITEM._serialized_end=122
  _CART._serialized_start=124
  _CART._serialized_end=178
  _ADDITEMTOCARTREQUEST._serialized_start=180
  _ADDITEMTOCARTREQUEST._serialized_end=257
  _UPDATEITEMQUANTITYREQUEST._serialized_start=259
  _UPDATEITEMQUANTITYREQUEST._serialized_end=341
  _REMOVEITEMFROMCARTREQUEST._serialized_start=343
  _REMOVEITEMFROMCARTREQUEST._serialized_end=407
  _GETCARTREQUEST._serialized_start=409
  _GETCARTREQUEST._serialized_end=442
  _CARTRESPONSE._serialized_start=444
  _CARTRESPONSE._serialized_end=484
  _CARTSERVICE._serialized_start=487
  _CARTSERVICE._serialized_end=768
# @@protoc_insertion_point(module_scope)
