# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog_events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61talog_events.proto\x12\x0e\x63\x61talog_events\"\xea\x01\n\x13ProductUpdatedEvent\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x0b\n\x03sku\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\x14\n\x0cmanufacturer\x18\t \x01(\t\x12\x0e\n\x06status\x18\n \x01(\t\x12\x0f\n\x07version\x18\x0b \x01(\x03\x12\x12\n\nupdated_at\x18\x0c \x01(\t\"\xea\x01\n\x13ProductCreatedEvent\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x0b\n\x03sku\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\x14\n\x0cmanufacturer\x18\t \x01(\t\x12\x0e\n\x06status\x18\n \x01(\t\x12\x0f\n\x07version\x18\x0b \x01(\x03\x12\x12\n\ncreated_at\x18\x0c \x01(\t\"6\n\x13ProductDeletedEvent\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\tBo\n\x1c\x63om.community.catalog.eventsB\x12\x43\x61talogEventsProtoZ;github.com/community-platform/catalog_events;catalog_eventsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.community.catalog.eventsB\022CatalogEventsProtoZ;github.com/community-platform/catalog_events;catalog_events'
  _PRODUCTUPDATEDEVENT._serialized_start=41
  _PRODUCTUPDATEDEVENT._serialized_end=275
  _PRODUCTCREATEDEVENT._serialized_start=278
  _PRODUCTCREATEDEVENT._serialized_end=512
  _PRODUCTDELETEDEVENT._serialized_start=514
  _PRODUCTDELETEDEVENT._serialized_end=568
# @@protoc_insertion_point(module_scope)
