# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkout_events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63heckout_events.proto\x12\x0f\x63heckout_events\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x16\x43heckoutInitiatedEvent\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rt_id\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"z\n\x16InventoryReservedEvent\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rt_id\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x93\x01\n\x1fInventoryReservationFailedEvent\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rt_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampBs\n\x1d\x63om.community.checkout.eventsB\x13\x43heckoutEventsProtoZ=github.com/community-platform/checkout_events;checkout_eventsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkout_events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.community.checkout.eventsB\023CheckoutEventsProtoZ=github.com/community-platform/checkout_events;checkout_events'
  _CHECKOUTINITIATEDEVENT._serialized_start=75
  _CHECKOUTINITIATEDEVENT._serialized_end=197
  _INVENTORYRESERVEDEVENT._serialized_start=199
  _INVENTORYRESERVEDEVENT._serialized_end=321
  _INVENTORYRESERVATIONFAILEDEVENT._serialized_start=324
  _INVENTORYRESERVATIONFAILEDEVENT._serialized_end=471
# @@protoc_insertion_point(module_scope)
