# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkout.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63heckout.proto\x12\x08\x63heckout\"*\n\x17InitiateCheckoutRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"/\n\x18InitiateCheckoutResponse\x12\x13\n\x0b\x63heckout_id\x18\x01 \x01(\t\"/\n\x18GetCheckoutStatusRequest\x12\x13\n\x0b\x63heckout_id\x18\x01 \x01(\t\"i\n\x19GetCheckoutStatusResponse\x12\x13\n\x0b\x63heckout_id\x18\x01 \x01(\t\x12&\n\x05state\x18\x02 \x01(\x0e\x32\x17.checkout.CheckoutState\x12\x0f\n\x07message\x18\x03 \x01(\t*m\n\rCheckoutState\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\r\n\tCANCELLED\x10\x05\x32\xca\x01\n\x0f\x43heckoutService\x12Y\n\x10InitiateCheckout\x12!.checkout.InitiateCheckoutRequest\x1a\".checkout.InitiateCheckoutResponse\x12\\\n\x11GetCheckoutStatus\x12\".checkout.GetCheckoutStatusRequest\x1a#.checkout.GetCheckoutStatusResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkout_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKOUTSTATE._serialized_start=277
  _CHECKOUTSTATE._serialized_end=386
  _INITIATECHECKOUTREQUEST._serialized_start=28
  _INITIATECHECKOUTREQUEST._serialized_end=70
  _INITIATECHECKOUTRESPONSE._serialized_start=72
  _INITIATECHECKOUTRESPONSE._serialized_end=119
  _GETCHECKOUTSTATUSREQUEST._serialized_start=121
  _GETCHECKOUTSTATUSREQUEST._serialized_end=168
  _GETCHECKOUTSTATUSRESPONSE._serialized_start=170
  _GETCHECKOUTSTATUSRESPONSE._serialized_end=275
  _CHECKOUTSERVICE._serialized_start=389
  _CHECKOUTSERVICE._serialized_end=591
# @@protoc_insertion_point(module_scope)
