# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n\x05Money\x12\x15\n\rcurrency_code\x18\x01 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x02 \x01(\x03\"\x96\x01\n\x07\x41\x64\x64ress\x12\x11\n\tfull_name\x18\x01 \x01(\t\x12\x16\n\x0estreet_address\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x16\n\x0estate_province\x18\x04 \x01(\t\x12\x13\n\x0bpostal_code\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\x12\x14\n\x0cphone_number\x18\x07 \x01(\t\"t\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x18\n\x10unit_price_cents\x18\x04 \x01(\x03\x12\x19\n\x11total_price_cents\x18\x05 \x01(\x03\"x\n\x0cSagaMetadata\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0ereply_to_topic\x18\x04 \x01(\tBh\n*com.community.platform.shared.proto.commonP\x01Z8github.com/community-platform/shared/proto/common;commonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.community.platform.shared.proto.commonP\001Z8github.com/community-platform/shared/proto/common;common'
  _MONEY._serialized_start=57
  _MONEY._serialized_end=109
  _ADDRESS._serialized_start=112
  _ADDRESS._serialized_end=262
  _ORDERITEM._serialized_start=264
  _ORDERITEM._serialized_end=380
  _SAGAMETADATA._serialized_start=382
  _SAGAMETADATA._serialized_end=502
# @@protoc_insertion_point(module_scope)
