# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoice_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15invoice_service.proto\x12\x07invoice\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n\x16GenerateInvoiceCommand\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12(\n\x0f\x62illing_address\x18\x04 \x01(\x0b\x32\x0f.common.Address\x12 \n\x05items\x18\x05 \x03(\x0b\x32\x11.common.OrderItem\x12\x16\n\x0esubtotal_cents\x18\x06 \x01(\x03\x12\x16\n\x0eshipping_cents\x18\x07 \x01(\x03\x12\x11\n\ttax_cents\x18\x08 \x01(\x03\x12\x16\n\x0e\x64iscount_cents\x18\t \x01(\x03\x12\x13\n\x0btotal_cents\x18\n \x01(\x03\x12\x1e\n\x16payment_transaction_id\x18\x0b \x01(\t\"~\n\x15InvoiceGeneratedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x12\n\ninvoice_id\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\x17\n\x0finvoice_pdf_url\x18\x04 \x01(\t\"h\n\x1cInvoiceGenerationFailedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\tBk\n+com.community.platform.shared.proto.invoiceP\x01Z:github.com/community-platform/shared/proto/invoice;invoiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+com.community.platform.shared.proto.invoiceP\001Z:github.com/community-platform/shared/proto/invoice;invoice'
  _GENERATEINVOICECOMMAND._serialized_start=82
  _GENERATEINVOICECOMMAND._serialized_end=401
  _INVOICEGENERATEDEVENT._serialized_start=403
  _INVOICEGENERATEDEVENT._serialized_end=529
  _INVOICEGENERATIONFAILEDEVENT._serialized_start=531
  _INVOICEGENERATIONFAILEDEVENT._serialized_end=635
# @@protoc_insertion_point(module_scope)
