# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\x05order\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n\x12\x43reateOrderCommand\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12)\n\x10shipping_address\x18\x03 \x01(\x0b\x32\x0f.common.Address\x12(\n\x0f\x62illing_address\x18\x04 \x01(\x0b\x32\x0f.common.Address\x12 \n\x05items\x18\x05 \x03(\x0b\x32\x11.common.OrderItem\x12\x16\n\x0esubtotal_cents\x18\x06 \x01(\x03\x12\x16\n\x0eshipping_cents\x18\x07 \x01(\x03\x12\x11\n\ttax_cents\x18\x08 \x01(\x03\x12\x16\n\x0e\x64iscount_cents\x18\t \x01(\x03\x12\x13\n\x0btotal_cents\x18\n \x01(\x03\x12\x1e\n\x16payment_transaction_id\x18\x0b \x01(\t\"s\n\x11OrderCreatedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x13\n\x0btotal_cents\x18\x04 \x01(\x03\"c\n\x18OrderCreationFailedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\tBe\n)com.community.platform.shared.proto.orderP\x01Z6github.com/community-platform/shared/proto/order;orderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.community.platform.shared.proto.orderP\001Z6github.com/community-platform/shared/proto/order;order'
  _CREATEORDERCOMMAND._serialized_start=78
  _CREATEORDERCOMMAND._serialized_end=418
  _ORDERCREATEDEVENT._serialized_start=420
  _ORDERCREATEDEVENT._serialized_end=535
  _ORDERCREATIONFAILEDEVENT._serialized_start=537
  _ORDERCREATIONFAILEDEVENT._serialized_end=636
# @@protoc_insertion_point(module_scope)
