# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12order_events.proto\x12\x0corder_events\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n\x11OrderCreatedEvent\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"{\n\x18OrderCreationFailedEvent\x12\x0f\n\x07saga_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampBg\n\x1a\x63om.community.order.eventsB\x10OrderEventsProtoZ7github.com/community-platform/order_events;order_eventsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.community.order.eventsB\020OrderEventsProtoZ7github.com/community-platform/order_events;order_events'
  _ORDERCREATEDEVENT._serialized_start=69
  _ORDERCREATEDEVENT._serialized_end=187
  _ORDERCREATIONFAILEDEVENT._serialized_start=189
  _ORDERCREATIONFAILEDEVENT._serialized_end=312
# @@protoc_insertion_point(module_scope)
