# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x07payment\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n\x15ProcessPaymentCommand\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x04 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x1e\n\x16payment_method_details\x18\x07 \x01(\t\"|\n\x14RefundPaymentCommand\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x03 \x01(\x03\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\xa0\x01\n\x15PaymentProcessedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x05 \x01(\x03\x12\x0e\n\x06status\x18\x06 \x01(\t\"o\n\x12PaymentFailedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\x94\x01\n\x14PaymentRefundedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x1d\n\x15refund_transaction_id\x18\x02 \x01(\t\x12\x1f\n\x17original_transaction_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x04 \x01(\x03\x42k\n+com.community.platform.shared.proto.paymentP\x01Z:github.com/community-platform/shared/proto/payment;paymentb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+com.community.platform.shared.proto.paymentP\001Z:github.com/community-platform/shared/proto/payment;payment'
  _PROCESSPAYMENTCOMMAND._serialized_start=82
  _PROCESSPAYMENTCOMMAND._serialized_end=276
  _REFUNDPAYMENTCOMMAND._serialized_start=278
  _REFUNDPAYMENTCOMMAND._serialized_end=402
  _PAYMENTPROCESSEDEVENT._serialized_start=405
  _PAYMENTPROCESSEDEVENT._serialized_end=565
  _PAYMENTFAILEDEVENT._serialized_start=567
  _PAYMENTFAILEDEVENT._serialized_end=678
  _PAYMENTREFUNDEDEVENT._serialized_start=681
  _PAYMENTREFUNDEDEVENT._serialized_end=829
# @@protoc_insertion_point(module_scope)
