# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_read_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import product_pb2 as product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproduct_read_service.proto\x12\x0cproduct_read\x1a\rproduct.proto\"#\n\x15GetProductByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x17\n\x15GetAllProductsRequest\"<\n\x16GetAllProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\"&\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"<\n\x16SearchProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\".\n\x18GetProductDetailsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t2\xe6\x02\n\x12ProductReadService\x12G\n\x0eGetProductById\x12#.product_read.GetProductByIdRequest\x1a\x10.product.Product\x12[\n\x0eGetAllProducts\x12#.product_read.GetAllProductsRequest\x1a$.product_read.GetAllProductsResponse\x12[\n\x0eSearchProducts\x12#.product_read.SearchProductsRequest\x1a$.product_read.SearchProductsResponse\x12M\n\x11GetProductDetails\x12&.product_read.GetProductDetailsRequest\x1a\x10.product.ProductBe\n(com.community.catalog.proto.product_readP\x01Z7github.com/community-platform/product_read;product_readb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_read_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(com.community.catalog.proto.product_readP\001Z7github.com/community-platform/product_read;product_read'
  _GETPRODUCTBYIDREQUEST._serialized_start=59
  _GETPRODUCTBYIDREQUEST._serialized_end=94
  _GETALLPRODUCTSREQUEST._serialized_start=96
  _GETALLPRODUCTSREQUEST._serialized_end=119
  _GETALLPRODUCTSRESPONSE._serialized_start=121
  _GETALLPRODUCTSRESPONSE._serialized_end=181
  _SEARCHPRODUCTSREQUEST._serialized_start=183
  _SEARCHPRODUCTSREQUEST._serialized_end=221
  _SEARCHPRODUCTSRESPONSE._serialized_start=223
  _SEARCHPRODUCTSRESPONSE._serialized_end=283
  _GETPRODUCTDETAILSREQUEST._serialized_start=285
  _GETPRODUCTDETAILSREQUEST._serialized_end=331
  _PRODUCTREADSERVICE._serialized_start=334
  _PRODUCTREADSERVICE._serialized_end=692
# @@protoc_insertion_point(module_scope)
