# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"=\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"9\n\x0eSearchResponse\x12\'\n\x08products\x18\x01 \x03(\x0b\x32\x15.search.ProductResult\"r\n\rProductResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x11\n\timage_url\x18\x06 \x01(\t2P\n\rSearchService\x12?\n\x0eSearchProducts\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseBC\n\x14\x63om.community.searchZ+github.com/community-platform/search;searchb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.community.searchZ+github.com/community-platform/search;search'
  _SEARCHREQUEST._serialized_start=24
  _SEARCHREQUEST._serialized_end=85
  _SEARCHRESPONSE._serialized_start=87
  _SEARCHRESPONSE._serialized_end=144
  _PRODUCTRESULT._serialized_start=146
  _PRODUCTRESULT._serialized_end=260
  _SEARCHSERVICE._serialized_start=262
  _SEARCHSERVICE._serialized_end=342
# @@protoc_insertion_point(module_scope)
