# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14wallet_service.proto\x12\x06wallet\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x12\x44\x65\x62itWalletCommand\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x03 \x01(\x03\x12\x0e\n\x06reason\x18\x04 \x01(\t\"t\n\x13\x43reditWalletCommand\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x03 \x01(\x03\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\x8a\x01\n\x12WalletDebitedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1c\n\x14\x64\x65\x62ited_amount_cents\x18\x03 \x01(\x03\x12\x1d\n\x15\x63urrent_balance_cents\x18\x04 \x01(\x03\"a\n\x16WalletDebitFailedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\x8c\x01\n\x13WalletCreditedEvent\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.common.SagaMetadata\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1d\n\x15\x63redited_amount_cents\x18\x03 \x01(\x03\x12\x1d\n\x15\x63urrent_balance_cents\x18\x04 \x01(\x03\x42h\n*com.community.platform.shared.proto.walletP\x01Z8github.com/community-platform/shared/proto/wallet;walletb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.community.platform.shared.proto.walletP\001Z8github.com/community-platform/shared/proto/wallet;wallet'
  _DEBITWALLETCOMMAND._serialized_start=79
  _DEBITWALLETCOMMAND._serialized_end=194
  _CREDITWALLETCOMMAND._serialized_start=196
  _CREDITWALLETCOMMAND._serialized_end=312
  _WALLETDEBITEDEVENT._serialized_start=315
  _WALLETDEBITEDEVENT._serialized_end=453
  _WALLETDEBITFAILEDEVENT._serialized_start=455
  _WALLETDEBITFAILEDEVENT._serialized_end=552
  _WALLETCREDITEDEVENT._serialized_start=555
  _WALLETCREDITEDEVENT._serialized_end=695
# @@protoc_insertion_point(module_scope)
