// Code generated by protoc-gen-go. DO NOT EDIT.
package checkout_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type SagaCompletedEvent struct {
	state         protoimpl.MessageState
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3"`
	TotalPriceCents int64                 `protobuf:"varint,4,opt,name=total_price_cents,json=totalPriceCents,proto3"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaCompletedEvent) Reset() { *x = SagaCompletedEvent{} }
func (x *SagaCompletedEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SagaCompletedEvent) ProtoMessage() {}

type SagaFailedEvent struct {
	state         protoimpl.MessageState
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3"`
	FailedStep    string                 `protobuf:"bytes,4,opt,name=failed_step,json=failedStep,proto3"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaFailedEvent) Reset() { *x = SagaFailedEvent{} }
func (x *SagaFailedEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SagaFailedEvent) ProtoMessage() {}
