apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tracing
  labels:
    app: tracing
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tracing
  template:
    metadata:
      labels:
        app: tracing
    spec:
      containers:
        - name: tracing
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
