apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-invoice
  labels:
    app: invoice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
        - name: invoice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
