apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-list-price
  labels:
    app: list-price
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: list-price
  template:
    metadata:
      labels:
        app: list-price
    spec:
      containers:
        - name: list-price
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
