// source: catalog_events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global = function () {
  if (this) {
    return this;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  return Function("return this")();
}.call(null);

goog.exportSymbol("proto.catalog_events.ProductCreatedEvent", null, global);
goog.exportSymbol("proto.catalog_events.ProductDeletedEvent", null, global);
goog.exportSymbol("proto.catalog_events.ProductUpdatedEvent", null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.catalog_events.ProductUpdatedEvent = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.catalog_events.ProductUpdatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.catalog_events.ProductUpdatedEvent.displayName =
    "proto.catalog_events.ProductUpdatedEvent";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.catalog_events.ProductCreatedEvent = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.catalog_events.ProductCreatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.catalog_events.ProductCreatedEvent.displayName =
    "proto.catalog_events.ProductCreatedEvent";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.catalog_events.ProductDeletedEvent = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.catalog_events.ProductDeletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.catalog_events.ProductDeletedEvent.displayName =
    "proto.catalog_events.ProductDeletedEvent";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.catalog_events.ProductUpdatedEvent.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.catalog_events.ProductUpdatedEvent.toObject(
      opt_includeInstance,
      this,
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.catalog_events.ProductUpdatedEvent} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.catalog_events.ProductUpdatedEvent.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        productId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        name: jspb.Message.getFieldWithDefault(msg, 2, ""),
        description: jspb.Message.getFieldWithDefault(msg, 3, ""),
        price: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
        quantity: jspb.Message.getFieldWithDefault(msg, 5, 0),
        sku: jspb.Message.getFieldWithDefault(msg, 6, ""),
        imageUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
        category: jspb.Message.getFieldWithDefault(msg, 8, ""),
        manufacturer: jspb.Message.getFieldWithDefault(msg, 9, ""),
        status: jspb.Message.getFieldWithDefault(msg, 10, ""),
        version: jspb.Message.getFieldWithDefault(msg, 11, 0),
        updatedAt: jspb.Message.getFieldWithDefault(msg, 12, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.catalog_events.ProductUpdatedEvent}
 */
proto.catalog_events.ProductUpdatedEvent.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.catalog_events.ProductUpdatedEvent();
  return proto.catalog_events.ProductUpdatedEvent.deserializeBinaryFromReader(
    msg,
    reader,
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.catalog_events.ProductUpdatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.catalog_events.ProductUpdatedEvent}
 */
proto.catalog_events.ProductUpdatedEvent.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setProductId(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setName(value);
          break;
        case 3:
          var value = /** @type {string} */ (reader.readString());
          msg.setDescription(value);
          break;
        case 4:
          var value = /** @type {number} */ (reader.readDouble());
          msg.setPrice(value);
          break;
        case 5:
          var value = /** @type {number} */ (reader.readInt32());
          msg.setQuantity(value);
          break;
        case 6:
          var value = /** @type {string} */ (reader.readString());
          msg.setSku(value);
          break;
        case 7:
          var value = /** @type {string} */ (reader.readString());
          msg.setImageUrl(value);
          break;
        case 8:
          var value = /** @type {string} */ (reader.readString());
          msg.setCategory(value);
          break;
        case 9:
          var value = /** @type {string} */ (reader.readString());
          msg.setManufacturer(value);
          break;
        case 10:
          var value = /** @type {string} */ (reader.readString());
          msg.setStatus(value);
          break;
        case 11:
          var value = /** @type {number} */ (reader.readInt64());
          msg.setVersion(value);
          break;
        case 12:
          var value = /** @type {string} */ (reader.readString());
          msg.setUpdatedAt(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.catalog_events.ProductUpdatedEvent.serializeBinaryToWriter(
      this,
      writer,
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.catalog_events.ProductUpdatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.catalog_events.ProductUpdatedEvent.serializeBinaryToWriter = function (
  message,
  writer,
) {
  var f = undefined;
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(4, f);
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(5, f);
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(6, f);
  }
  f = message.getImageUrl();
  if (f.length > 0) {
    writer.writeString(7, f);
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(8, f);
  }
  f = message.getManufacturer();
  if (f.length > 0) {
    writer.writeString(9, f);
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(10, f);
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt64(11, f);
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(12, f);
  }
};

/**
 * optional string product_id = 1;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getProductId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setProductId = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string name = 2;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getName = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setName = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string description = 3;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getDescription =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 3, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setDescription = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional double price = 4;
 * @return {number}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getPrice = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0)
  );
};

/**
 * @param {number} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setPrice = function (value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};

/**
 * optional int32 quantity = 5;
 * @return {number}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getQuantity = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};

/**
 * @param {number} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setQuantity = function (
  value,
) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

/**
 * optional string sku = 6;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getSku = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setSku = function (value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};

/**
 * optional string image_url = 7;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getImageUrl = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setImageUrl = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 7, value);
};

/**
 * optional string category = 8;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getCategory = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setCategory = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 8, value);
};

/**
 * optional string manufacturer = 9;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getManufacturer =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 9, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setManufacturer = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 9, value);
};

/**
 * optional string status = 10;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getStatus = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setStatus = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 10, value);
};

/**
 * optional int64 version = 11;
 * @return {number}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getVersion = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};

/**
 * @param {number} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setVersion = function (
  value,
) {
  return jspb.Message.setProto3IntField(this, 11, value);
};

/**
 * optional string updated_at = 12;
 * @return {string}
 */
proto.catalog_events.ProductUpdatedEvent.prototype.getUpdatedAt = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductUpdatedEvent} returns this
 */
proto.catalog_events.ProductUpdatedEvent.prototype.setUpdatedAt = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 12, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.catalog_events.ProductCreatedEvent.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.catalog_events.ProductCreatedEvent.toObject(
      opt_includeInstance,
      this,
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.catalog_events.ProductCreatedEvent} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.catalog_events.ProductCreatedEvent.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        productId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        name: jspb.Message.getFieldWithDefault(msg, 2, ""),
        description: jspb.Message.getFieldWithDefault(msg, 3, ""),
        price: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
        quantity: jspb.Message.getFieldWithDefault(msg, 5, 0),
        sku: jspb.Message.getFieldWithDefault(msg, 6, ""),
        imageUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
        category: jspb.Message.getFieldWithDefault(msg, 8, ""),
        manufacturer: jspb.Message.getFieldWithDefault(msg, 9, ""),
        status: jspb.Message.getFieldWithDefault(msg, 10, ""),
        version: jspb.Message.getFieldWithDefault(msg, 11, 0),
        createdAt: jspb.Message.getFieldWithDefault(msg, 12, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.catalog_events.ProductCreatedEvent}
 */
proto.catalog_events.ProductCreatedEvent.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.catalog_events.ProductCreatedEvent();
  return proto.catalog_events.ProductCreatedEvent.deserializeBinaryFromReader(
    msg,
    reader,
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.catalog_events.ProductCreatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.catalog_events.ProductCreatedEvent}
 */
proto.catalog_events.ProductCreatedEvent.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setProductId(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setName(value);
          break;
        case 3:
          var value = /** @type {string} */ (reader.readString());
          msg.setDescription(value);
          break;
        case 4:
          var value = /** @type {number} */ (reader.readDouble());
          msg.setPrice(value);
          break;
        case 5:
          var value = /** @type {number} */ (reader.readInt32());
          msg.setQuantity(value);
          break;
        case 6:
          var value = /** @type {string} */ (reader.readString());
          msg.setSku(value);
          break;
        case 7:
          var value = /** @type {string} */ (reader.readString());
          msg.setImageUrl(value);
          break;
        case 8:
          var value = /** @type {string} */ (reader.readString());
          msg.setCategory(value);
          break;
        case 9:
          var value = /** @type {string} */ (reader.readString());
          msg.setManufacturer(value);
          break;
        case 10:
          var value = /** @type {string} */ (reader.readString());
          msg.setStatus(value);
          break;
        case 11:
          var value = /** @type {number} */ (reader.readInt64());
          msg.setVersion(value);
          break;
        case 12:
          var value = /** @type {string} */ (reader.readString());
          msg.setCreatedAt(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.catalog_events.ProductCreatedEvent.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.catalog_events.ProductCreatedEvent.serializeBinaryToWriter(
      this,
      writer,
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.catalog_events.ProductCreatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.catalog_events.ProductCreatedEvent.serializeBinaryToWriter = function (
  message,
  writer,
) {
  var f = undefined;
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(4, f);
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(5, f);
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(6, f);
  }
  f = message.getImageUrl();
  if (f.length > 0) {
    writer.writeString(7, f);
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(8, f);
  }
  f = message.getManufacturer();
  if (f.length > 0) {
    writer.writeString(9, f);
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(10, f);
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt64(11, f);
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(12, f);
  }
};

/**
 * optional string product_id = 1;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getProductId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setProductId = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string name = 2;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getName = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setName = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string description = 3;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getDescription =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 3, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setDescription = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional double price = 4;
 * @return {number}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getPrice = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0)
  );
};

/**
 * @param {number} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setPrice = function (value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};

/**
 * optional int32 quantity = 5;
 * @return {number}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getQuantity = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};

/**
 * @param {number} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setQuantity = function (
  value,
) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

/**
 * optional string sku = 6;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getSku = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setSku = function (value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};

/**
 * optional string image_url = 7;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getImageUrl = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setImageUrl = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 7, value);
};

/**
 * optional string category = 8;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getCategory = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setCategory = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 8, value);
};

/**
 * optional string manufacturer = 9;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getManufacturer =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 9, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setManufacturer = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 9, value);
};

/**
 * optional string status = 10;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getStatus = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setStatus = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 10, value);
};

/**
 * optional int64 version = 11;
 * @return {number}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getVersion = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};

/**
 * @param {number} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setVersion = function (
  value,
) {
  return jspb.Message.setProto3IntField(this, 11, value);
};

/**
 * optional string created_at = 12;
 * @return {string}
 */
proto.catalog_events.ProductCreatedEvent.prototype.getCreatedAt = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductCreatedEvent} returns this
 */
proto.catalog_events.ProductCreatedEvent.prototype.setCreatedAt = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 12, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.catalog_events.ProductDeletedEvent.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.catalog_events.ProductDeletedEvent.toObject(
      opt_includeInstance,
      this,
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.catalog_events.ProductDeletedEvent} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.catalog_events.ProductDeletedEvent.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        productId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        sku: jspb.Message.getFieldWithDefault(msg, 2, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.catalog_events.ProductDeletedEvent}
 */
proto.catalog_events.ProductDeletedEvent.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.catalog_events.ProductDeletedEvent();
  return proto.catalog_events.ProductDeletedEvent.deserializeBinaryFromReader(
    msg,
    reader,
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.catalog_events.ProductDeletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.catalog_events.ProductDeletedEvent}
 */
proto.catalog_events.ProductDeletedEvent.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setProductId(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setSku(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.catalog_events.ProductDeletedEvent.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.catalog_events.ProductDeletedEvent.serializeBinaryToWriter(
      this,
      writer,
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.catalog_events.ProductDeletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.catalog_events.ProductDeletedEvent.serializeBinaryToWriter = function (
  message,
  writer,
) {
  var f = undefined;
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
};

/**
 * optional string product_id = 1;
 * @return {string}
 */
proto.catalog_events.ProductDeletedEvent.prototype.getProductId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductDeletedEvent} returns this
 */
proto.catalog_events.ProductDeletedEvent.prototype.setProductId = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string sku = 2;
 * @return {string}
 */
proto.catalog_events.ProductDeletedEvent.prototype.getSku = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.catalog_events.ProductDeletedEvent} returns this
 */
proto.catalog_events.ProductDeletedEvent.prototype.setSku = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

goog.object.extend(exports, proto.catalog_events);
