import type { Metadata } from "next";
import localFont from "next/font/local"; // Import localFont
import "./globals.css";

// Define local fonts
const geistSans = localFont({
  src: "../../public/fonts/Geist-Regular.woff2", // Adjust path based on your structure
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMono-Regular.woff2", // Adjust path based on your structure
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
