// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: catalog_events.proto

package catalog_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,9,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdatedEvent) Reset() {
	*x = ProductUpdatedEvent{}
	mi := &file_catalog_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdatedEvent) ProtoMessage() {}

func (x *ProductUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ProductUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_catalog_events_proto_rawDescGZIP(), []int{0}
}

func (x *ProductUpdatedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdatedEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductUpdatedEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductUpdatedEvent) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductUpdatedEvent) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductUpdatedEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductUpdatedEvent) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *ProductUpdatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductUpdatedEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProductUpdatedEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ProductCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,9,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreatedEvent) Reset() {
	*x = ProductCreatedEvent{}
	mi := &file_catalog_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreatedEvent) ProtoMessage() {}

func (x *ProductCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreatedEvent.ProtoReflect.Descriptor instead.
func (*ProductCreatedEvent) Descriptor() ([]byte, []int) {
	return file_catalog_events_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCreatedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCreatedEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCreatedEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductCreatedEvent) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductCreatedEvent) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductCreatedEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductCreatedEvent) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *ProductCreatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductCreatedEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProductCreatedEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ProductDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDeletedEvent) Reset() {
	*x = ProductDeletedEvent{}
	mi := &file_catalog_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDeletedEvent) ProtoMessage() {}

func (x *ProductDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDeletedEvent.ProtoReflect.Descriptor instead.
func (*ProductDeletedEvent) Descriptor() ([]byte, []int) {
	return file_catalog_events_proto_rawDescGZIP(), []int{2}
}

func (x *ProductDeletedEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductDeletedEvent) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

var File_catalog_events_proto protoreflect.FileDescriptor

const file_catalog_events_proto_rawDesc = "" +
	"\n" +
	"\x14catalog_events.proto\x12\x0ecatalog_events\"\xdc\x02\n" +
	"\x13ProductUpdatedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\"\n" +
	"\fmanufacturer\x18\t \x01(\tR\fmanufacturer\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xdc\x02\n" +
	"\x13ProductCreatedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\"\n" +
	"\fmanufacturer\x18\t \x01(\tR\fmanufacturer\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"F\n" +
	"\x13ProductDeletedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03skuBo\n" +
	"\x1ccom.community.catalog.eventsB\x12CatalogEventsProtoZ;github.com/community-platform/catalog_events;catalog_eventsb\x06proto3"

var (
	file_catalog_events_proto_rawDescOnce sync.Once
	file_catalog_events_proto_rawDescData []byte
)

func file_catalog_events_proto_rawDescGZIP() []byte {
	file_catalog_events_proto_rawDescOnce.Do(func() {
		file_catalog_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_events_proto_rawDesc), len(file_catalog_events_proto_rawDesc)))
	})
	return file_catalog_events_proto_rawDescData
}

var file_catalog_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_events_proto_goTypes = []any{
	(*ProductUpdatedEvent)(nil), // 0: catalog_events.ProductUpdatedEvent
	(*ProductCreatedEvent)(nil), // 1: catalog_events.ProductCreatedEvent
	(*ProductDeletedEvent)(nil), // 2: catalog_events.ProductDeletedEvent
}
var file_catalog_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_events_proto_init() }
func file_catalog_events_proto_init() {
	if File_catalog_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_events_proto_rawDesc), len(file_catalog_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_events_proto_goTypes,
		DependencyIndexes: file_catalog_events_proto_depIdxs,
		MessageInfos:      file_catalog_events_proto_msgTypes,
	}.Build()
	File_catalog_events_proto = out.File
	file_catalog_events_proto_goTypes = nil
	file_catalog_events_proto_depIdxs = nil
}
