apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-refund
  labels:
    app: refund
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: refund
  template:
    metadata:
      labels:
        app: refund
    spec:
      containers:
        - name: refund
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
