# Stage 1: Build the application using Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

# Copy shared proto files
COPY shared/proto /shared/proto

# Copy the service's pom.xml and source
COPY services/catalog/product-write/pom.xml ./pom.xml
COPY services/catalog/product-write/src ./src

# Build the application
RUN --mount=type=cache,target=/root/.m2 mvn -B package -DskipTests -Dmaven.wagon.http.readTimeout=120000 -Dmaven.wagon.http.retryHandler.count=5

# Stage 2: Create the final, lightweight container
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

# Create a non-root user and group
RUN groupadd --system springapp && useradd --system --uid 1001 --gid springapp springapp
USER springapp

# Copy the built JAR file from the 'build' stage
COPY --from=build --chown=springapp:springapp /app/target/product-write-1.0.0-SNAPSHOT.jar ./app.jar
EXPOSE 8081
# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]