apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-discount-engine
  labels:
    app: discount-engine
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discount-engine
  template:
    metadata:
      labels:
        app: discount-engine
    spec:
      containers:
        - name: discount-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
