apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-log-forwarder
  labels:
    app: log-forwarder
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: log-forwarder
  template:
    metadata:
      labels:
        app: log-forwarder
    spec:
      containers:
        - name: log-forwarder
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
