apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-search-index
  labels:
    app: search-index
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: search-index
  template:
    metadata:
      labels:
        app: search-index
    spec:
      containers:
        - name: search-index
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
