apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-brand
  labels:
    app: brand
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: brand
  template:
    metadata:
      labels:
        app: brand
    spec:
      containers:
        - name: brand
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
