apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: config
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
