apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-search-query
  labels:
    app: search-query
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: search-query
  template:
    metadata:
      labels:
        app: search-query
    spec:
      containers:
        - name: search-query
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {}
          env: []
